import {
  canSharePartnerLocation,
  getPartnerTrackingCapabilities,
  issueCaseAccessToken,
  parsePartnerCaseStatus,
  verifyCaseAccessToken,
  isSecurePartnerEndpoint
} from '../server/partnerTracking.ts';
import { section, assert, assertEqual } from './helpers.ts';

const env = {
  AUTHORIZED_PARTNER_API_URL: 'https://partner.example/dispatch',
  AUTHORIZED_PARTNER_API_KEY: 'server-only-key',
  AUTHORIZED_PARTNER_STATUS_URL: 'https://partner.example/status',
  AUTHORIZED_PARTNER_LOCATION_URL: 'https://partner.example/location',
  AUTHORIZED_PARTNER_STOP_URL: 'https://partner.example/stop',
  AUTHORIZED_PARTNER_TRACKING_SECRET: '01234567890123456789012345678901'
};
const now = Date.parse('2026-09-24T10:00:00.000Z');

section('Authorized partner tracking boundary — partner facts only, dual consent, fail-closed');
assertEqual(isSecurePartnerEndpoint('http://partner.example/status'), false, 'tracking rejects non-HTTPS partner endpoint');
assertEqual(isSecurePartnerEndpoint('https://partner.example/status?token=secret'), false, 'tracking rejects credential/query-bearing endpoint');
assertEqual(getPartnerTrackingCapabilities(env).caseStatusEnabled, true, 'case status requires configured authorized endpoints and signing secret');
assertEqual(getPartnerTrackingCapabilities(env).liveTrackingEnabled, true, 'live tracking requires all separate authorized endpoints');

const issued = issueCaseAccessToken(env, 'SOS-123', 'PARTNER-456', now);
assert(Boolean(issued), 'case capability is issued only for a real reference ID');
const capability = verifyCaseAccessToken(env, issued?.token, now + 1000);
assertEqual(capability?.sosId, 'SOS-123', 'case token is bound to the SOS id');
assertEqual(verifyCaseAccessToken(env, issued?.token + 'tampered', now), null, 'tampered case token is rejected');
assertEqual(verifyCaseAccessToken(env, issued?.token, now + 86_400_001), null, 'expired case token is rejected');

const current = parsePartnerCaseStatus({
  sosId: 'SOS-123', referenceId: 'PARTNER-456', partnerAccepted: true,
  trackingAccepted: true, caseNumber: 'CASE-99',
  assignedResponder: { id: 'UNIT-1', name: 'Responder One' },
  distanceKm: 4.2, etaMinutes: 12, stage: 'EN_ROUTE',
  updatedAt: new Date(now).toISOString()
}, capability!);
assert(Boolean(current), 'matching partner case facts are accepted');
assertEqual(current?.caseNumber, 'CASE-99', 'case number is partner-supplied, never generated by the client');
assertEqual(current?.etaMinutes, 12, 'ETA is partner-supplied');
assert(canSharePartnerLocation(current!, now + 1000), 'GPS sharing requires fresh partner acceptance and assignment');

const mismatched = parsePartnerCaseStatus({
  sosId: 'OTHER-SOS', referenceId: 'PARTNER-456', partnerAccepted: true,
  trackingAccepted: true, caseNumber: 'CASE-99',
  assignedResponder: { id: 'UNIT-1', name: 'Responder One' }, stage: 'EN_ROUTE',
  updatedAt: new Date(now).toISOString()
}, capability!);
assertEqual(mismatched, null, 'cross-case status cannot be displayed or used for GPS');
const stale = { ...current!, updatedAt: new Date(now - 61_000).toISOString() };
assertEqual(canSharePartnerLocation(stale, now), false, 'stale partner status stops GPS sharing');
const closed = { ...current!, stage: 'CLOSED' as const };
assertEqual(canSharePartnerLocation(closed, now), false, 'closed partner case stops GPS sharing');
const noAssignment = { ...current!, assignedResponder: undefined };
assertEqual(canSharePartnerLocation(noAssignment, now), false, 'GPS sharing requires a partner-assigned responder');
